---
title: "My Life"
editor: visual
---

Standard CVs, for some reason, start from the most recent activities/job.

Here, I like to look back and remind things I have build, projects I have contributed to, people I have met and friends made along the journey. Starting from the ...beginning

**Chapter 1: the birth of an explorer**

My research career started one day back in 1991 at the Department of Internal Medicine (Univeristy of Ferrara, IT) when my friend and colleague (now Prof) Giovanni Zuliani suggested to look into a lipid particle, recently discovered. It was called Lipoprotein (a). Function unknown but probably high blood levels were associated with high cardiovascular risk. Luckily the Head of Department (Prof Fellin) knew an expert in lipoproteins measurement and few months later I was working with Prof Kostner in his Biochemistry department in Graz. Centrifuge, ultracentrifuge, pipetting, eppendorf, agarose, SDS-PAGE, isoelectrofocusing, ELISA , DELFIA. What a fun days. I remember, I was in the lab already at 4 am. excited and anxious to carry on my next experiment. I had the idea to characterize the size of this particle by measuring its mobility on acrylamide gel. It was a good idea but prof Kostner informed me that prof Utermann (University of Innsbruck) had the same idea. In the end we published the finding together.

I learned also how to measure the phenotype of apo E through electrofocusing.

Meanwhile Prof Zuliani was carrying on a cohort study in a small remote italian village with people reaching old age in pretty good health condition and he was studying the predictors of longevity. We did some analysis in order to assess the level of Lp(a) and its isoforms along with the apo E phenotyping on a sample of octuagenarians. And we did apo E because already at that time we knew about the association of Apo E with Alzheimer's disease.

Lots of sample, lots of data. I started to perform analysis by my own and the interest for data and statistics has grown since then. I started with a statistical package on a Apple computer. I was leaving the lab very late because on the same desktop was installed the first version of DOOM. I don't remember if it was a legal or pirated version. I remember the fun and the competition among the lab folk. Thank you Anton for teaching me all the lab techniques , helping me with the car in that cold morning and for letting me win with DOOM.

I have been in Graz (I have been told that my anchestors were coming from that city, but this is the subject for another story) for one year. I went back to my home Department after working one year in the ward and in the outpatients clinic I had the opportunity to join the Friedrikson lab at NIH, Bethesda, USA. The lab belonging to the Molecular Disease Branch, NHLBI, was led by Bryan Brewer. Thank you Bryan and Bob for your patience with me. Again I was challenged with the mistery of Lp(a). The idea was to take the blood from people with Familial Hypercholesterolemia (high apo B) and people without apo B and inject radioiodinated Lp(a) and apo (a) to understand the metabolism (from the shape of the decay curve). So I learned to use the SAAM software to solve the equations for the decay and also collected a lot of urine samples (in the middle of the night too). Indeed I found apo(a) almost intact in the urine. Masato Nishiwaki was a researcher from Japan and I am so grateful I met him. He has been to kindest and most knowledgeable guy I have ever met. We spent so many hours talking about lipids, atherosclerosis and eating large peperoni pizzas (Domino) and drinking so many cans of beer. Thank you Masato for everything you did for me. I had nothing to give you in return. I remember Nao (Japan), Minna Hannuksela, Hassan Nazih. Building 10, 7 floor, has been our house for 2 years. Then finally I was offered with 5 years contract. Meanwhile I was collaborating with Dr Angelo Scanu team (thank you Celina) and I was intrigued by the idea to move to Chicago and continue to dive into the mistery of Lp(a).

Winter 1996. The worse time in my life. After few weeks I signed the contract with NIH my boss told me to go back in Italy because he managed to secure a permanent position at the Internal Medicine Department. So I had to say goodbye and cancel my 5 years contract at NIH. For Christmas I have been invited (with my wife) by my boss for dinner. During the meal my boss told me, seraphically, that I have to continue to do research abroad, no position was available, no job. At the age of 37 I had to reinvent myself.

**Chapter 2: choices and the good the bad and the hugly of the industry**

At that time, to work and learn at the Internal Medicine Department during the day I had (as many other of my generation) to work during the night in private clinics or in the emergency department to earn some money. During my specialization in Endocrinology and Metabolism (5 years) and my PhD (4 years) I was working at the University during the day for free. And my parents supported me in all my travelling. They invested in me. Thank you papa', thank you mamma.

Late 1997 I was struggling between my dream of a career in the academia (I always loved teaching) and the need for a job. I remember one day I started not going to the University every day any more. I was involved more and more with a job that eventually became permanent in a private clinic. Thank you Prof Pellegrini for letting me in. One day I felt like a stranger in the Department of Internal Medicine. I realized that the dream was over. I cried.

I have many memories of the private clinic. I developed aversion for religion, any religion or I should say fanatism, at that time. A 50 years old man died in front of his family (parents, wife, 2 daughters). He had a bleeding gastric ulcer and because his belief he refused the blood transfusion. I couldn't save him because his religion. And I started to ask myself if we really need god when we die. The answer was no. We die anyway. 

Early 1998. I was in the ambulatory of the private clinic and a commercial representative from Company A told me that the company was looking for a diabetologist. Then I met Alessandro. Alessandro Coppini. It was a blast. Immediate connection. I was taken. By the personality maybe. But was enough for me to move my family to Pisa. The house had the sea in front and the hills (with olive trees) on the back. Romantic. The ideal place to raise our first kid, Edoardo. But the birth took place in Venice. The North-East of Italy is my country. I was born and will die there, not in Italy but in Veneto.

Happy memories. In Company A I met the nicest guy in the industry. Pasquale Di Coste. Head of Marketing. What a gentleman. Known by every diabetologists in Italy. They were competing to have Pasquale attention or a call from him. Pasquale was generous, kind, knowledgeable, a listener, humble and leader at the same time. Also heavy smoker. In those years I learned everything we need to know in Medical Affairs. I did registration studies and registered a drug (combination) with few regulatory colleagues. At the same time I was visiting diabetologists on the territory with reps. I remember memorable dinners in Sicily, in Sardinia. I remember the hours spent in training reps. And after a while they were coming back and say that physicians were impressed by how the rep was showcasing our orals and insulins. I also remember developing a new CGM medical device (Continuous Glucose Monitoring) for measuring glucose for 72 hours. What a fun to analyse the data (Clarkson grid). But the second son was coming , Niccolo'. Money were again a concern. In addition in the overall picture I was missing the holistic approach. We had simvastatin and lacidipine but the company no vision for the disease, atherosclerosis.

So, Company B came in early 2000. The Marketing department was looking for MDs to be deployed on the territory to collaborate with Institutions, physicians and payers. At the beginning it was just educational training on DRG but then I developed my own area of expertise. I started to analyse data from hospitals, claims, EMR etc. And I was presenting the results to the Hospitals General Managers to let them understand the impact and value of the drugs in their hospitals and territory.

My analyses were somehow popular and I remember that I was performing all kind of analysis for labs, for neurologists, for cardiologists, reumatologists. So I learned that every specialty has different statistics. I started to give training on statistics at Universities. I have been working for the italian chapter of the OMERACT. Strikingly the Friuli Venezia Giulia region asked officially to Company B for my help to analyse their data and paid me a fellowship (thank you Dr Diego Vanuzzo). I remember dr Nicola Bottazzo, Head of the Laboratory from an Hospital from the North-East. I remember dr Sakis Themistoclakis (thank you Sakis for testing my heart for flutter).

With all the specialists I met we had very productive collaboration and many publication. Campnay B (reps) always had the doors open to their office thanks to this "service".

At that time I was mainly using Stata after SPSS, Statgraphics, Statistica, Systat and many more statistical packages. I think I have used them all. I started to look into the life of early statisticians to understand what sort of questions they had to develop statistical techniques. I bought many books and read and studied them all, avidly. Fermat, Descartes, Bernoulli, Gauss etc. I expanded my reading and read about Galileo Galilei and his fight against the dogma and I understood what science means. Liebnitz and Newton. Gauss, Riemann, Lobačevskij. We can't understand Einstein without knowing the giants before him. All of these giants were looking up. They were looking at the universe not just with the telescope but mainly with their brains, like Stephen Hawking did.

All of these great people were genious and led the progress of human kind, true leaders. But also humans. Karl Pearson (inventor of the measurement of the association) and Ronald Fisher (design of experiment, the rule of the p=0.05) were both Galton's students. But they had a fight. Ronald Fisher left the department and moved to the Rothamsted Experimental Station where he conducted "agricultural" experiments. Without that fight between strong personalities we would not have the statistical methodology that allow us to conduct trials. To become a farmer is not a bad idea after all. I spent my childhood in my family farm (45.90771368396219, 13.439667443246693). And this is what I am going to do after the retirement. Work the soil and take picture of the universe, this is the plan. Thank you Ronald Fisher to show me the way.

The analysis of claims and hospital data was very popular and colleagues from Company B were sending me data from every italian region for the analysis. Here I'd like to mention another gentleman. Gianni Dall'Asta. For 7 years we have been wrangling the italian territory and we were well known in so many hospitals. I remember two distric managers, Maria Grazia Fattori and Maria Grazia Sona. Commercial yes, but with the appropriate use of the medicines in mind. Great people and friends.

Then Simvastatin went generic, amlodipine was already a mature brand. Company B had to re-org. The consultant agency came in. The new face of the company turned out to be extremely commercial. Already at that time the healthcare system was asking for quality of the information. The biggest problem of any health care system when it comes to treatment of chronic disease is the compliance and adherence. Despite the investment, patients have an adherence of 50-60%. So the benefit promised by the trials won't happen. I saw this problem in the clinic and in the data. Many publications and books on this phenomenon, still largely unsolved. I believe that this is an area where the collaboration with institutions, GPs, pharmacies could be really fruitful and increase the appropriate use of the drugs while increasing the business. Win-win situation.

Few months later, in 2007, I left Company B and joined Company C. I changed city where, again, I did standard Medical Affairs activities. I was responsible for rosiglitazone. Few months later a meta-analysis from Nissen was suggesting CV risk (congestive failure). In 24 hour I repeated the analysis and found that by changing the method to deal with missing data the meta-analysis was not significant any more. This was admitted later by Nissen himself. But the damage was done and a good drug was killed in unclear circumstances. Three unremarkable years. Standard people (maybe big ego but scratching the surface..nothing). But I have been lucky and met Antonio Chiapperini. Marketing. The intellectual exchange has been always very interesting and stimulated my curiosity a lot. Music for example. Thank you Antonio for introducing me to Eddie Vedder. I still listen Pearl Jam, Stone Temple Pilots, Nirvana, Soundgarden while I lift weights, every day since 1982.

I remember the good relationship and the fun with the diabetologists community during the usual congresses (ADA, EASD). Thank you Prof Agostino Consoli for your friendship. Thank you Ele Ferrannini for your friendship. Thank you Stefano Del Prato. Thank you Enzo Bonora for the trust.

The company especially at Global and Regional level had no view on the disease. Only on brands. Not good enough for me.

Early 2010 I got a call from Company D. They were looking for someone taking over a big observational study (the NIS, PCD or RWE terminology was not known, yet). I happily joined the Development organization and led this 55000 patients study.

After the primary publication we had 60 more (one per country with different angles).Thank you Chantal Mathieu for supporting my story.

I was in heaven. By pooling together all the trials from the compound I was working on plus this observational study I had available 100.000 patients to mine. A gold mine.

Until then I was using STATA as statistical package. And it's a fantastic package used mainly by academia. Point and click and coding were both possible. The problem was the handling of the computer memory. 
Another challenge was that the studies data were stored in SAS which requires coding and learning the sintax. I learned statistics by myself why not learning how to code ? I started to learn coding. I learned SAS. Full immersion. It took awhile to master the underpinning concept. And I have understood another important lesson. A good medical advisor must know the basic of programming. The design of a good experiment, the reading of an article, asking advices to a statistician require some basic principle of programming.

I started to mine the data of other compounds and I was lucky and asked to setup a new team (Medical Analytics) to mine all the data we have but also to train the medical organization to become more data driven. I failed. I had 7 statisticians and I spent months to train those statisticians on the diseases in order to let them understand the design of the trials we had to mine. And spent months to educate medical colleagues on how to ask questions, how to shape queries in a language understandable by statisticians and programmers. But no time to show to the management what we were doing and the many publications we had already. Politics has never been my strength.

Early 2015, my professional life changed. The fashion and fluff took over. Big Data, RWE, Machine Learning. Just new names for old stuff. The new management was dazzled by these rings and bells. Payers and local decision makers want to have evidences on the value of the drugs with local data. I know how difficult is to have access to local data. Data from US are not applicable to Japan. In real life the drugs are used differently by different health care systems. Local data, local contracts to get the data, local policies for the anonimization. RWE teams have to be delocalized. I knew that by experience. One big RWE central team is not ideal. Company D decided otherwise. Three years later the central team was dissolved.

After years and millions spent for setting up platforms (plural on purpose) the key issue is still there, open. Or even worsened. The digital environment we are living in requires some familiarity with coding or at least the logic underpinning the coding. Without the notion of string we can't understand the text mining used to extract information from EMR or sentiment analysis from a social network. It's not just a technical detail. It's the core of the knowledge required to perform any job in the industry. A market research or survey without asking the right question too many times opens the door to ambiguous answers. It's also essential to understand the report from the CRM (customer relationship management system).
After SAS I learned R and now I perform pooling, data curation, meta-analysis, descriptive statistics, modeling, Machine Learning in R. This website is done with Quarto, a R package.

Anyways, I left the RWE team before its dissolution because I was asked to take over the Medical Affairs team responsible of drugs on the market since decades. I still have fun in slicing and dicing the data from old studies. I look into the disease not the drugs. And I get my analysis approved by ADA and EASD as posters.

